---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  creationTimestamp: null
  labels: {}
  name: hello-again-again-service
  namespace: acrossnamespace
spec:
  type: ClusterIP
  ports:
    # make the service available on this port
    - port: 80
      name: unsecure
      targetPort: 80
      protocol: TCP
    - port: 443
      name: secure
      targetPort: 443
      protocol: TCP
  selector:
    app: hello-again-again
