apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    control-plane.alpha.kubernetes.io/leader: '{"holderIdentity":"nginx-ingress-ingress-nginx-controller-b8767d776-cbj4z","leaseDurationSeconds":30,"acquireTime":"2020-10-02T13:14:27Z","renewTime":"2020-10-02T13:28:31Z","leaderTransitions":2}'
  creationTimestamp: "2020-07-21T11:21:04Z"
  name: ingress-controller-leader-nginx
  namespace: ingress-nginx
  resourceVersion: "19986746"
  selfLink: /api/v1/namespaces/ingress-nginx/configmaps/ingress-controller-leader-nginx
  uid: 26101471-b542-44c4-9d57-c4fa453a0b02
