---
# Source: nginx-ingress/templates/controller-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: nginx-ingress
    chart: nginx-ingress-1.33.0
    heritage: Helm
    release: default
  name: default-nginx-ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: default-nginx-ingress
subjects:
  - kind: ServiceAccount
    name: default-nginx-ingress
    namespace: default
