---
# Source: nginx-ingress/templates/controller-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: nginx-ingress
    chart: nginx-ingress-1.33.0
    heritage: Helm
    release: RELEASE-NAME
  name: RELEASE-NAME-nginx-ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: RELEASE-NAME-nginx-ingress
subjects:
  - kind: ServiceAccount
    name: RELEASE-NAME-nginx-ingress
    namespace: default
