---
# Source: nginx-ingress/templates/controller-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: nginx-ingress
    chart: nginx-ingress-1.33.0
    heritage: Helm
    release: RELEASE-NAME
  name: RELEASE-NAME-nginx-ingress
